{% set name = "pyjuliapkg" %}
{% set pypi_name = "juliapkg" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/juliapkg-{{ version }}.tar.gz
  sha256: f37e0c16a0706169cce039fc0bde3431e72c17464342f9aaf1b8922144e2058d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - semver >=3.0,<4.dev0

test:
  imports:
    - juliapkg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JuliaPy/pyjuliapkg
  summary: Julia version manager and package manager
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilesCranmer
    - mkitti
