{% set name = "pyjuliapkg" %}
{% set pypi_name = "juliapkg" %}
{% set version = "0.1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/juliapkg-{{ version }}.tar.gz
  sha256: 87fd29c5b1db58004a1be0c6fa6317156db5cc477c9ddfbe0ba2a7aa514057de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - semver >=3.0,<4.dev0
    - filelock >=3.16,<4.dev0

test:
  imports:
    - juliapkg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JuliaPy/pyjuliapkg
  summary: Julia version manager and package manager
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilesCranmer
    - mkitti
