{% set name = "pyjuliapkg" %}
{% set pypi_name = "juliapkg" %}
{% set version = "0.1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/juliapkg-{{ version }}.tar.gz
  sha256: 2716b6d5abcbeecb059794c569e40a6c7ec8ce2c66a4a56e01ac822d251e42a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - semver >=3.0,<4.dev0
    - filelock >=3.16,<4.dev0
    - tomlkit >=0.13.3,<0.14
    - tomli >=2.0,<3.dev0
    - click >=8.0,<9.0

test:
  imports:
    - juliapkg
  commands:
    - pip check
    - python -m juliapkg --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JuliaPy/pyjuliapkg
  summary: Julia version manager and package manager
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilesCranmer
    - mkitti
